version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/Frontend/Checkers-Frontend"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/Backend/Checkers-CommunicationService"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/Backend/Checkers-GameService"
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/Backend/Checkers-UserService"
    schedule:
      interval: "daily"
    target-branch: "develop"
