services:
  userservice:
    build: 
      context: /Backend
    restart: always
    ports:
      - 3031:3031
    command: node ./index.js
  gameservice:
    build: 
      context: /Backend
    restart: always
    ports:
      - 3032:3032
    command: node ./index.js