services:
  userservice:
    container_name: registry.digitalocean.com/checkers-cr/checkers:userservice
    build: 
      context: ./Backend
      args:
        - SERVICENAME=UserService
        - SERVICEDIR=Checkers-UserService
        - ARG_PORT=3031
    environment:
      - DB_PSW=${DB_PSW}
    restart: always
    ports:
      - 3031:3031
  gameservice:
    container_name: registry.digitalocean.com/checkers-cr/checkers:gameservice
    build: 
      context: ./Backend
      args:
        - SERVICENAME=GameService
        - SERVICEDIR=Checkers-GameService
        - ARG_PORT=3032
    environment:
      - DB_PSW=${DB_PSW}
    restart: always
    ports:
      - 3032:3032