require('./testWithUserService/signUpTest');
require('./testWithUserService/loginTest');
require('./testWithUserService/getProfileTest');
require('./testWithUserService/getLeaderBoardTest');
require('./testWithUserService/updateProfileTest');
require('./lobbyTest/buildLobbyTest');
require('./lobbyTest/getLobbiesTest');
require('./lobbyTest/joinLobbyTest');
require('./lobbyTest/deleteLobbyTest');
