# Automatic Versioning and Delivery
name: Delivery

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

env:
  REGISTRY: "registry.digitalocean.com/checkers-cr"
  IMAGE_NAME: "checkers"

jobs:
  getVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Debug
        run: |
          echo ${{ env.FullSemVer }}


  build_and_push:
    runs-on: ubuntu-latest
    needs: getVersion
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Debug
        run: |
          echo ${{ env.FullSemVer }}
