# Automatic Versioning and Delivery

name: Delivery

on:
  push:
    tags:
    - stagetest-*

jobs:
  getVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      #steps.gitversion.outputs.semVer

  build:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout files    
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: LucaSalvigni/Checkers
          tag_with_ref: true
          tag_with_sha: true
        
  deploy:
    needs: build   
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout files    
        uses: actions/checkout@v2
        
      - name: Get tag name
        uses: olegtarasov/get-tag@v2
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         
      - name: Provision Droplet and deploy container
        run: doctl compute droplet create "$GIT_TAG_NAME" --image docker-18-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait
