name: frontend

on:
  push:
    paths:
      - 'Frontend/Checkers-Frontend/**'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java_version: [ 14, 16, 18]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd Frontend/Checkers-Frontend
          npm ci
      - name: Test
        run: |
          cd Frontend/Checkers-Frontend
          npm run gulp test