name: gameservice

on:
  push:
    paths:
      - 'Backend/Checkers-GameService/**'
  workflow_dispatch:
  workflow_call:

env:
  GameService_PORT: 3032
  DB_PSW: ${{ secrets.DB_PSW }}
  GAME_KEY: ${{ secrets.GAME_KEY }}
  GAME_CERT: ${{ secrets.GAME_CERT }}
  CERTIFICATE: ${{ secrets.CERTIFICATE }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd Backend/Checkers-GameService
          npm ci
      - name: Test and build
        run: |
          cd Backend/Checkers-GameService
          npm run gulp test