name: gameservice

on:
  push:
    paths:
      - 'Backend/Checkers-GameService/**'
  pull_request:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    #if: startsWith(github.ref, 'refs/tags/v')
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          build-args: |
            SERVICENAME=GameService
            SERVICEDIR=Backend/Checkers-GameService
            ARG_PORT=3032
            ARG_DB_PSW=${{ secrets.DB_PSW }}
          tags: gameService:latest
  container-job:
    needs: docker-build
    runs-on: ubuntu-latest
    container: node:lts-alpine
    services:
      gameService:
        image: gameService
        ports:
          - 3032:3032
  build:
    needs: [docker-build, container-job]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd Backend/Checkers-GameService
          npm ci
      - name: Test and build
        run: |
          cd Backend/Checkers-GameService
          npm run gulp