name: gameservice

on:
  push:
    paths:
      - 'Backend/Checkers-GameService/**'
  #pull_request:
  workflow_dispatch:

env:
  PORT: 3032
  DB_PSW: ${{secrets.DB_PSW}}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd Backend/Checkers-GameService
          npm ci
      - name: Debugging info
        run: |
          cd Backend/Checkers-GameService
          npm run test       
      - name: Test and build
        run: |
          cd Backend/Checkers-GameService
          npm run gulp