name: gameservice

on:
  push:
    paths:
      - 'Backend/Checkers-GameService/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd Backend/Checkers-GameService
          npm ci
      - name: Run Server
        if: success() || failure() # Wait for previous steps to finish
        run: |
          cd Backend/Checkers-GameService
          node index.js
      - name: Test and build
        if: success() || failure() # Wait for server to start  
        run: |
          cd Backend/Checkers-GameService
          npm run gulp